# Generated by Django 6.0.6 on 2026-07-06 12:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('parent_child', 'Parent / Child'), ('spouse', 'Spouse')], max_length=20)),
                ('parent_link_type', models.CharField(blank=True, choices=[('biological', 'Biological'), ('adopted', 'Adopted'), ('step', 'Step-parent'), ('guardian', 'Guardian')], max_length=20)),
                ('spouse_status', models.CharField(blank=True, choices=[('current', 'Current'), ('divorced', 'Divorced'), ('deceased', 'Deceased spouse')], max_length=20)),
                ('marriage_order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='members.familymember')),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='members.familymember')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='trees.familytree')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'from_member', 'to_member'), name='unique_relationship_edge')],
            },
        ),
    ]
