# Generated by Django 6.0.6 on 2026-07-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='kind',
            field=models.CharField(choices=[('parent_child', 'Parent / Child'), ('spouse', 'Spouse'), ('sibling', 'Sibling')], max_length=20),
        ),
    ]
