# Generated by Django 6.0.6 on 2026-07-06 12:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=255)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('biography', models.TextField(blank=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('is_living', models.BooleanField(default=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('burial_location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='member_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='trees.familytree')),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
    ]
